# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        tools_db_provider:
            entity:
                class: App\Entity\User
                property: username

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/admin
            anonymous: ~
            provider: tools_db_provider
            form_login:
                default_target_path: /admin/
                login_path: login
                check_path: login
            logout:
                path: logout

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_SUPERADMIN }
        - { path: ^/label, roles: ROLE_SUPERADMIN }
        - { path: ^/print, roles: ROLE_SUPERADMIN }
