app:
    resource: '../src/Controller/'
    type: annotation

app_admin:
    resource: '../src/Controller/Admin/'
    type: annotation
    prefix: '/admin'

logout:
    path: '/admin/logout'

admin:
    path: '/admin'
